version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: rusty
      POSTGRES_DB: rusty
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: debug
      APP_SERVER_HOST: 0.0.0.0
      APP_SERVER_PORT: 8080
      DATABASE_URL: postgres://rusty:password@postgres/rusty # needed for diesel migrations
      APP_DATABASE_URL: postgres://rusty:password@postgres/rusty
      APP_DATABASE_TEST_URL: postgres://rusty:password@postgres/rusty_test
    depends_on:
      - postgres
